#####################################################################################################################
01. What are the people's names that contribute in this project?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?nameContributor WHERE {
  ?project            rdf:type                   ldwpo:LDWProject   .
  ?project            ldwpo:name                 ?nameProject       .
  ?project            ldwpo:ldWorkflow           ?ldworkflow        .
  ?ldworkflow         ldwpo:firstLdwStep         ?step              .
  ?ldworkflow         ldwpo:ldWorkflowExecution  ?workflowExecution .
  ?step               (ldwpo:nextStep)*          ?linkedStep        .
  ?linkedStep         ldwpo:ldwStepExecution     ?stepExecution     .
  ?workflowExecution  ldwpo:ldwStepExecution     ?stepExecution     .
  ?stepExecution      ldwpo:contributor          ?contributor       .
  ?contributor        ldwpo:name                 ?nameContributor   .  
} ORDER BY ?project

#####################################################################################################################
02. What is the person’s name that create this project?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?nameCreator WHERE {
  ?project  rdf:type       ldwpo:LDWProject .
  ?project  ldwpo:name     ?nameProject     .
  ?project  ldwpo:creator  ?creator         .
  ?creator  ldwpo:name     ?nameCreator     .  
} ORDER BY ?project

#####################################################################################################################
03. What is the project’s name?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject WHERE {
  ?project  rdf:type    ldwpo:LDWProject .
  ?project  ldwpo:name  ?nameProject     .
} ORDER BY ?project

#####################################################################################################################
04. What were the employed tools in this project?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?nameTool WHERE {
  ?project     rdf:type            ldwpo:LDWProject .
  ?project     ldwpo:name          ?nameProject     .
  ?project     ldwpo:ldWorkflow    ?ldworkflow      .
  ?ldworkflow  ldwpo:firstLdwStep  ?step            .
  ?step        (ldwpo:nextStep)*   ?linkedStep      .
  ?linkedStep  ldwpo:tool          ?tool            .
  ?tool        ldwpo:name          ?nameTool        .  
} ORDER BY ?project

#####################################################################################################################
05. What are the input datasets of this project?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?nameDataset WHERE {
  ?project       rdf:type            ldwpo:LDWProject  .
  ?project       ldwpo:name          ?nameProject      .
  ?project       ldwpo:ldWorkflow    ?ldworkflow       .
  ?ldworkflow    ldwpo:firstLdwStep  ?step             .
  ?step          (ldwpo:nextStep)*   ?linkedStep       .
  ?linkedStep    ldwpo:inputDataset  ?inputDataset     .
  ?inputDataset  ldwpo:name          ?nameDataset      .  
} ORDER BY ?project

#####################################################################################################################
06. What are the datasets of this project?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?nameDataset WHERE {
  {
    SELECT ?nameProject ?nameDataset WHERE {
      ?project       rdf:type            ldwpo:LDWProject  .
      ?project       ldwpo:name          ?nameProject      .
      ?project       ldwpo:ldWorkflow    ?ldworkflow       .
      ?ldworkflow    ldwpo:firstLdwStep  ?step             .
      ?step          (ldwpo:nextStep)*   ?linkedStep       .
      ?linkedStep    ldwpo:inputDataset  ?inputDataset     .
      ?inputDataset  ldwpo:name          ?nameDataset      .  
    }
  }
  UNION 
  {
    SELECT ?nameProject ?nameDataset WHERE {
      ?project       rdf:type             ldwpo:LDWProject  .
      ?project       ldwpo:name           ?nameProject      .
      ?project       ldwpo:ldWorkflow     ?ldworkflow       .
      ?ldworkflow    ldwpo:firstLdwStep   ?step             .
      ?step          (ldwpo:nextStep)*    ?linkedStep       .
      ?linkedStep    ldwpo:outputDataset  ?outputDataset    .
      ?outputDataset  ldwpo:name          ?nameDataset      .  
    }
  }
} ORDER BY ?project

#####################################################################################################################
07. What are the stages of this project?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?nameStage WHERE {
  ?project       rdf:type            ldwpo:LDWProject  .
  ?project       ldwpo:name          ?nameProject      .
  ?project       ldwpo:ldWorkflow    ?ldworkflow       .
  ?ldworkflow    ldwpo:firstLdwStep  ?step             .
  ?step          (ldwpo:nextStep)*   ?linkedStep       .
  ?linkedStep    ldwpo:task          ?task             .
  ?stage         rdf:type            ldwpo:Stage       .
  ?stage         ldwpo:task          ?task             . 
  ?stage         ldwpo:name          ?nameStage        . 
} ORDER BY ?project

#####################################################################################################################
08. What are the transformations in this project?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?description WHERE {
  ?project       rdf:type            ldwpo:LDWProject  .
  ?project       ldwpo:name          ?nameProject      .
  ?project       ldwpo:ldWorkflow    ?ldworkflow       .
  ?ldworkflow    ldwpo:firstLdwStep  ?step             .
  ?step          (ldwpo:nextStep)*   ?linkedStep       .
  ?linkedStep    ldwpo:description   ?description      .
  ?ldworkflow    ldwpo:ldwStep       ?linkedStep       .
}

#####################################################################################################################
09. What is the output dataset of this stage?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?nameDataset WHERE {
  ?project       rdf:type            ldwpo:LDWProject  .
  ?project       ldwpo:name          ?nameProject      .
  ?project       ldwpo:ldWorkflow    ?ldworkflow       .
  ?ldworkflow    ldwpo:firstLdwStep  ?step             .
  ?step          (ldwpo:nextStep)*   ?linkedStep       .
  ?linkedStep    ldwpo:inputDataset  ?inputDataset     .
  ?inputDataset  ldwpo:name          ?nameDataset      .  
} ORDER BY ?project

#####################################################################################################################
10. What steps are done in this stage?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?ldWorkflow ?stage ?linkedStep WHERE {
  ?project       rdf:type            ldwpo:LDWProject  .
  ?stage         rdf:type            ldwpo:Stage       .
  ?step          rdf:type            ldwpo:LDWStep     .
  ?ldWorkflow    rdf:type            ldwpo:LDWorkflow  .
  ?project       ldwpo:name          ?nameProject      .
  ?project       ldwpo:ldWorkflow    ?ldWorkflow       .
  ?ldWorkflow    ldwpo:firstLdwStep  ?step             .
  ?step          (ldwpo:nextStep)*   ?linkedStep       .
  ?linkedStep    ldwpo:task          ?task             .
  ?stage         ldwpo:task          ?task             .  
} ORDER BY ?project ?stage

#####################################################################################################################
11. What is the previous step of this step?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?ldWorkflow ?linkedStep ?previousStep WHERE {
  ?project       rdf:type            ldwpo:LDWProject  .
  ?step          rdf:type            ldwpo:LDWStep     .
  ?linkedStep    rdf:type            ldwpo:LDWStep     .
  ?previousStep  rdf:type            ldwpo:LDWStep     .
  ?ldWorkflow    rdf:type            ldwpo:LDWorkflow  .
  ?project       ldwpo:name          ?nameProject      .
  ?project       ldwpo:ldWorkflow    ?ldWorkflow       .
  ?ldWorkflow    ldwpo:firstLdwStep  ?step             .
  ?ldWorkflow    ldwpo:ldwStep       ?linkedStep       .
  ?ldWorkflow    ldwpo:ldwStep       ?previousStep     .
  ?step          (ldwpo:nextStep)*   ?linkedStep       .
  ?linkedStep    ldwpo:previousStep  ?previousStep     .
} ORDER BY ?project

#####################################################################################################################
12. What is the next step of this step?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?ldWorkflow ?linkedStep ?nextStep WHERE {
  ?project       rdf:type            ldwpo:LDWProject  .
  ?step          rdf:type            ldwpo:LDWStep     .
  ?linkedStep    rdf:type            ldwpo:LDWStep     .
  ?previousStep  rdf:type            ldwpo:LDWStep     .
  ?ldWorkflow    rdf:type            ldwpo:LDWorkflow  .
  ?project       ldwpo:name          ?nameProject      .
  ?project       ldwpo:ldWorkflow    ?ldWorkflow       .
  ?ldWorkflow    ldwpo:firstLdwStep  ?step             .
  ?ldWorkflow    ldwpo:ldwStep       ?linkedStep       .
  ?ldWorkflow    ldwpo:ldwStep       ?nextStep         .
  ?step          (ldwpo:nextStep)*   ?linkedStep       .
  ?linkedStep    ldwpo:nextStep      ?nextStep         .
} ORDER BY ?project

#####################################################################################################################
13. What is the format of the dataset?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?nameDataset WHERE {
  {
    SELECT ?nameProject ?nameDataset WHERE {
      ?project       rdf:type            ldwpo:LDWProject  .
      ?project       ldwpo:name          ?nameProject      .
      ?project       ldwpo:ldWorkflow    ?ldworkflow       .
      ?ldworkflow    ldwpo:firstLdwStep  ?step             .
      ?step          (ldwpo:nextStep)*   ?linkedStep       .
      ?linkedStep    ldwpo:inputDataset  ?inputDataset     .
      ?inputDataset  ldwpo:name          ?nameDataset      .  
      ?inputDataset  ldwpo:name          ?nameDataset      .  
	  
    }
  }
  UNION 
  {
    SELECT ?nameProject ?nameDataset WHERE {
      ?project       rdf:type             ldwpo:LDWProject  .
      ?project       ldwpo:name           ?nameProject      .
      ?project       ldwpo:ldWorkflow     ?ldworkflow       .
      ?ldworkflow    ldwpo:firstLdwStep   ?step             .
      ?step          (ldwpo:nextStep)*    ?linkedStep       .
      ?linkedStep    ldwpo:outputDataset  ?outputDataset    .
      ?outputDataset  ldwpo:name          ?nameDataset      .  
    }
  }
} ORDER BY ?project

#####################################################################################################################
14. What are the project’s goals?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?goal WHERE {
  ?project  rdf:type    ldwpo:LDWProject .
  ?project  ldwpo:name  ?nameProject     .
  ?project  ldwpo:goal  ?goal            .
}

#####################################################################################################################
15. What is the license of the dataset?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameDataset ?nameLicense WHERE {
  ?dataset  rdf:type       ldwpo:Dataset .
  ?license  rdf:type       ldwpo:License .
  ?dataset  ldwpo:name     ?nameDataset  .
  ?dataset  ldwpo:license  ?license      .
  ?license  ldwpo:name     ?nameLicense  .
}

#####################################################################################################################
16. What kind of task is this step?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?step ?task ?taskDescription WHERE {
  ?step  rdf:type           ldwpo:LDWStep     .
  ?task  rdf:type           ldwpo:Task        .
  ?step  ldwpo:task         ?task             .
  ?task  ldwpo:description  ?taskDescription  .
}

#####################################################################################################################
17. What tasks do this tool be applied?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?task ?tool WHERE {
  ?step  rdf:type    ldwpo:LDWStep  .
  ?task  rdf:type    ldwpo:Task     .
  ?tool  rdf:type    ldwpo:Tool     .
  ?step  ldwpo:task  ?task          .
  ?step  ldwpo:tool  ?tool          .
}

#####################################################################################################################
18. Who are the people that contribute in this project?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?nameProject ?nameContributor WHERE {
  ?project            rdf:type                   ldwpo:LDWProject   .
  ?project            ldwpo:name                 ?nameProject       .
  ?project            ldwpo:ldWorkflow           ?ldworkflow        .
  ?ldworkflow         ldwpo:firstLdwStep         ?step              .
  ?ldworkflow         ldwpo:ldWorkflowExecution  ?workflowExecution .
  ?step               (ldwpo:nextStep)*          ?linkedStep        .
  ?linkedStep         ldwpo:ldwStepExecution     ?stepExecution     .
  ?workflowExecution  ldwpo:ldwStepExecution     ?stepExecution     .
  ?stepExecution      ldwpo:contributor          ?contributor       .
  ?contributor        ldwpo:name                 ?nameContributor   .  
} ORDER BY ?project

#####################################################################################################################
19. Who is responsible for this step?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?stepExecution ?nameContributor WHERE {
  ?stepExecution  rdf:type           ldwpo:LDWStepExecution  .
  ?stepExecution  ldwpo:contributor  ?contributor            .
  ?contributor    ldwpo:name         ?nameContributor        .  
}

#####################################################################################################################
20. Where is the input dataset stored?
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?dataset ?location WHERE {
  ?dataset   rdf:type            ldwpo:Dataset  .
  ?step      rdf:type            ldwpo:LDWStep  .  
  ?location  rdf:type            ldwpo:Location .
  ?step      ldwpo:inputDataset  ?dataset       .
  ?dataset   ldwpo:location      ?location      .
}

#####################################################################################################################
21. Where is the output dataset stored?
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?dataset ?location WHERE {
  ?dataset   rdf:type             ldwpo:Dataset  .
  ?step      rdf:type             ldwpo:LDWStep  .  
  ?location  rdf:type             ldwpo:Location .
  ?step      ldwpo:outputDataset  ?dataset       .
  ?dataset   ldwpo:location       ?location      .
}

#####################################################################################################################
22. How is the input dataset stored?
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?dataset ?fileFormat WHERE {
  ?dataset     rdf:type            ldwpo:Dataset    .
  ?step        rdf:type            ldwpo:LDWStep    .  
  ?FileFormat  rdf:type            ldwpo:FileFormat .
  ?step        ldwpo:inputDataset  ?dataset         .
  ?dataset     ldwpo:fileFormat    ?fileFormat      .
}

#####################################################################################################################
23. How is the output dataset stored?
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?dataset ?fileFormat WHERE {
  ?dataset     rdf:type             ldwpo:Dataset    .
  ?step        rdf:type             ldwpo:LDWStep    .  
  ?FileFormat  rdf:type             ldwpo:FileFormat .
  ?step        ldwpo:outputDataset  ?dataset         .
  ?dataset     ldwpo:fileFormat     ?fileFormat      .
}

#####################################################################################################################
24. When was the step executed?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?stepExecution ?startedDate WHERE {
  ?stepExecution  rdf:type           ldwpo:LDWStepExecution  .
  ?stepExecution  ldwpo:startedDate  ?startedDate            .
}

#####################################################################################################################
25. When did the workflow start?
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?workflowExecution ?startedDate WHERE {
  ?workflowExecution  rdf:type           ldwpo:LDWorkflowExecution  .
  ?workflowExecution  ldwpo:startedDate  ?startedDate               .
}

#####################################################################################################################
26. When did the workflow finish? 
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ldwpo: <http://ldwpo.aksw.org/terms/1.0/>

SELECT DISTINCT ?workflowExecution ?endedDate WHERE {
  ?workflowExecution  rdf:type         ldwpo:LDWorkflowExecution  .
  ?workflowExecution  ldwpo:endedDate  ?endedDate               .
}
